run_tests:
  image: python:3.11
  before_script: 
    - apt update && apt install git -y && pip install -r requirements.txt
  script:
    - python manage.py runserver 0.0.0.0:8000 &

build_image:
  image: docker:26.1.3-cli
  services: 
    - docker:26.1.3-dind
  variables:
    DOCKER_TLS_DIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build --no-cache -t hamda998/e-learn:e-learning .
    - docker push hamda998/e-learn:e-learning

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@ec2-54-237-148-20.compute-1.amazonaws.com "
        sudo docker ps -aq | sudo xargs docker stop | sudo xargs docker rm &&
        sudo docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD &&
        sudo docker run -d -p 8000:8000 hamda998/e-learn:e-learning"